### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by sskhokhar** [mean-expert-official/loopback-sdk-builder#173]
There is a syntax error when Fireloop command is executed. Following are its traces.

C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\@mean-expert\fireloop\
bin\fireloop.js:43
  let loopbacked = `loopback:${cmd}`;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by jonathan-casarrubias** [comment]
Hi @sskhokhar thanks for reaching out..

Hey so, this issue is related to fireloop cli? 

````sh
$ fireloop
````

I can assume it is, yes I will change that for var to allow backwards compatibility.
