### ISSUE TITLE
Issues with loopback-component-remote-ctx

### ISSUE THREAD

**Issue by Destreyf** [mean-expert-official/loopback-sdk-builder#191]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X] 2.1.0-beta.16
- [ ] Other

Write other if any:

#### Please add a description for your issue:
I'm running loopback-component-remote-ctx and when i try to generate the SDK i get the following error: 
```
Generating: C:\loopback-api\client\sdk/services/custom/District.ts
undefined:25
  throw err;
  ^

TypeError: ejs:59
    57|   var postData;
    58|   if (httpVerb == 'POST' || httpVerb == 'PUT' || httpVerb == 'PATCH') {
 >> 59|     postData = action.accepts;
    60|   }
    61|   // SET ROUTE PARAMS
    62|   var routeParams = action.accepts

Cannot read property 'toUpperCase' of undefined
    at capitalize (C:\loopback-api\node_modules\@mean-expert\loopback-sdk-builder\lib\angular2\index.js:638:19)
    at params.forEach (C:\loopback-api\node_modules\@mean-expert\loopback-sdk-builder\lib\angular2\index.js:488:13)
    at Array.forEach (native)
    at Object.buildMethodParams (C:\loopback-api\node_modules\@mean-expert\loopback-sdk-builder\lib\angular2\index.js:482:12)
    at eval (eval at <anonymous> (C:\loopback-api\node_modules\@mean-expert\loopback-sdk-builder\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:51:141)
    at Array.forEach (native)
    at eval (eval at <anonymous> (C:\loopback-api\node_modules\@mean-expert\loopback-sdk-builder\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:947)
    at eval (eval at <anonymous> (C:\loopback-api\node_modules\@mean-expert\loopback-sdk-builder\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:101:19)
    at C:\loopback-api\node_modules\@mean-expert\loopback-sdk-builder\node_modules\ejs\lib\ejs.js:255:15
    at Object.exports.render (C:\loopback-api\node_modules\@mean-expert\loopback-sdk-builder\node_modules\ejs\lib\ejs.js:293:13)
```

I believe this is caused because the loopback-component-remote-ctx module modifies the parameters of some of the methods to add an instance of the remote-ctx to it, its pretty easy to disable this and generate the SDK but i haven't had a chance to test if this results in broken a broken SDK when the module is re-enabled.

I will do more debugging to see if i can come up with more information to simplify this.

**Comment by Destreyf** [comment]
In the configuration for the loopback-component-remote-ctx it allows me to specify the argName, i'm wondering if we could check for that and maybe ignore it if needed.

**Comment by Destreyf** [comment]
Upon looking further into this module, i think this could be resolved at the same time as #190 

loopback-component-remote-ctx actually builds an argument as such: 

```js
method.accepts.push({
  arg: REMOTE_ARG,
  description: '**Do not implement in clients**.',
  type: Object,
  injectCtx: true,
  http: {
    source: 'context'
  }
});

So if http.source === 'context' we could probably safely ignore this argument.

**Comment by jonathan-casarrubias** [comment]
Hi @Destreyf I was actually about to say that, I think that is basically the same issue,

Do yo think is ok to keep it in just 1 issue?

**Comment by Destreyf** [comment]
Yes, i say we keep it in #190, i've actually got a PR that fixes this that i just submitted if you're interested.

**Comment by Destreyf** [comment]
Closing in favor of #190
