### ISSUE TITLE
Potential mistype on replaceById method

### ISSUE THREAD

**Issue by stancheta** [mean-expert-official/loopback-sdk-builder#252]
#### What type of issue are you creating?
- [X] Bug

#### What version of this module are you using?
- [X] 2.1.0-rc.n (2.1 Release Candidate n)

Write other if any:

#### Please add a description for your issue:

Hey @jonathan-casarrubias, 

I got an error from using the replaceById function on one of my models:
```
Unhandled error for request POST /AdtCoachings/:id/replace: Error: id property (idCoaching) cannot be updated from :id to 2
    at Function.DataAccessObject.replaceById (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-datasource-juggler/lib/dao.js:2867:15)
    at SharedMethod.invoke (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/strong-remoting/lib/shared-method.js:262:25)
    at HttpContext.invoke (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/strong-remoting/lib/http-context.js:295:12)
    at phaseInvoke (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/strong-remoting/lib/remote-objects.js:647:9)
    at runHandler (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-phase/lib/phase.js:135:5)
    at iterate (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-phase/node_modules/async/lib/async.js:162:9)
    at runHandlers (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-phase/lib/phase.js:144:13)
    at iterate (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at /home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-phase/node_modules/async/lib/async.js:157:25
    at /home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at execStack (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/strong-remoting/lib/remote-objects.js:492:7)
    at RemoteObjects.execHooks (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/strong-remoting/lib/remote-objects.js:496:10)
    at phaseBeforeInvoke (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/strong-remoting/lib/remote-objects.js:643:10)
    at runHandler (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-phase/lib/phase.js:135:5)
    at iterate (/home/steven/Documents/webdev/rambutanPsqlAccess/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
```

I corrected this by replacing `':id'` with `id` on service/core/base.service.ts, line 343.

For context, third line from the bottom:
```
  /**
   * @method replaceById
   * @author Jonathan Casarrubias <t: johncasarrubias, gh: mean-expert-official>
   * @license MIT
   * @description
   * Generic replaceById method
   */
  public replaceById<T>(id: any, data: any = {}): Observable<T> {
    return this.request('POST', [
      LoopBackConfig.getPath(),
      LoopBackConfig.getApiVersion(),
      this.model.getModelDefinition().plural,
      ':id', 'replace'
    ].join('/'), undefined, undefined, { data }).map((data: T) => this.model.factory(data));
  }
```

Best, 
Steven

**Comment by jonathan-casarrubias** [comment]
Hey @stancheta thanks for reporting!!

I see actually the ':id' is correct, what is wrong is that the ID Value is not being passed to the request, it should be like this

````js
  /**
   * @method replaceById
   * @author Jonathan Casarrubias <t: johncasarrubias, gh: mean-expert-official>
   * @license MIT
   * @description
   * Generic replaceById method
   */
  public replaceById<T>(id: any, data: any = {}): Observable<T> {
    return this.request('POST', [
      LoopBackConfig.getPath(),
      LoopBackConfig.getApiVersion(),
      this.model.getModelDefinition().plural,
      ':id', 'replace'
    ].join('/'), { id }, undefined, { data }).map((data: T) => this.model.factory(data));
  }
````

I will add a patch for this and  send it in the RC4 version

Cheers
Jon

**Comment by stancheta** [comment]
Ah I see, thanks for the detailed response!

Best,
Steven
