### ISSUE TITLE
(NEW) IO Module

### ISSUE THREAD

**Issue by rajweb** [mean-expert-official/loopback-sdk-builder#325]
#### What type of issue are you creating?
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-rc.n (2.1 Release Candidate n)

Write other if any:

#### Please add a description for your issue
Hello,
 i am new in loopback/mean.expert and try to broadcast data from server side and also from client. using fileloop.io realtime data sycroniztion work as charm. but i require to broadcast data from server side (eg. take BTC rate from other website on server/api and broadcast it to our client).
 i am try using it by NEW IO Module Example but it not works. code given below:

**API(loopback2.0):-**
file: /boot/io-test.js

`module.exports = function (app) {
  app.on('started', function () {
    app.mx.IO.emit('test', 'Hello World');
    app.mx.IO.on('test', function (message) {
      console.log('MESSAGE: ', message);
    });
  });
};`

**APP(angular2):-**
file: app.component.ts
```
import { Component, OnInit } from '@angular/core';
import { RealTime } from '../shared/sdk/services';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor(private realTime: RealTime) {  this.realTime.IO.emit('test', 'hello publish it');
  	 this.realTime.IO.emit('test', 'raj angular');
     this.realTime.IO.on('test').subscribe((msg: any) => console.log('Realtime Cli Msg ='+ msg));
  }

  ngOnInit() {
  }

}

```

**Got Client Side error on Console:-**

```
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'emit' of undefined
TypeError: Cannot read property 'emit' of undefined
    at new HomeComponent (http://localhost:4200/main.bundle.js:853:25)
    at new Wrapper_HomeComponent (/AppModule/HomeComponent/wrapper.ngfactory.js:7:18)
    at CompiledTemplate.proxyViewClass.View_HomeComponent_Host0.createInternal (/AppModule/HomeComponent/host.ngfactory.js:15:29)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:96164:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:96620:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:47296:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:67593:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:78259:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:27437:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:27404:26)
    at http://localhost:4200/vendor.bundle.js:27340:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:27340:29)
    at ActivateRoutes.activate (http://localhost:4200/vendor.bundle.js:27314:14)
    at http://localhost:4200/vendor.bundle.js:26882:22
ErrorHandler.handleError @ error_handler.js:50
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:246
Zone.runGuarded @ zone.js:129
_loop_1 @ zone.js:429
drainMicroTaskQueue @ zone.js:438
Promise.resolve (async)
scheduleQueueDrain @ zone.js:391
scheduleMicroTask @ zone.js:399
ZoneDelegate.scheduleTask @ zone.js:258
Zone.scheduleMicroTask @ zone.js:165
scheduleResolveOrReject @ zone.js:518
ZoneAwarePromise.then @ zone.js:604
ZoneAwarePromise.all @ zone.js:584
JitCompiler._loadModules @ compiler.js:172
JitCompiler._compileModuleAndComponents @ compiler.js:124
JitCompiler.compileModuleAsync @ compiler.js:90
PlatformRef_._bootstrapModuleWithZone @ application_ref.js:388
PlatformRef_.bootstrapModule @ application_ref.js:363
596 @ main.ts:12
__webpack_require__ @ bootstrap b2b7e48…:52
1262 @ main.bundle.js:14
__webpack_require__ @ bootstrap b2b7e48…:52
webpackJsonpCallback @ bootstrap b2b7e48…:23
(anonymous) @ main.bundle.js:1
error_handler.js:55ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:55
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:246
Zone.runGuarded @ zone.js:129
_loop_1 @ zone.js:429
drainMicroTaskQueue @ zone.js:438
Promise.resolve (async)
scheduleQueueDrain @ zone.js:391
scheduleMicroTask @ zone.js:399
ZoneDelegate.scheduleTask @ zone.js:258
Zone.scheduleMicroTask @ zone.js:165
scheduleResolveOrReject @ zone.js:518
ZoneAwarePromise.then @ zone.js:604
ZoneAwarePromise.all @ zone.js:584
JitCompiler._loadModules @ compiler.js:172
JitCompiler._compileModuleAndComponents @ compiler.js:124
JitCompiler.compileModuleAsync @ compiler.js:90
PlatformRef_._bootstrapModuleWithZone @ application_ref.js:388
PlatformRef_.bootstrapModule @ application_ref.js:363
596 @ main.ts:12
__webpack_require__ @ bootstrap b2b7e48…:52
1262 @ main.bundle.js:14
__webpack_require__ @ bootstrap b2b7e48…:52
webpackJsonpCallback @ bootstrap b2b7e48…:23
(anonymous) @ main.bundle.js:1
error_handler.js:56Error: Uncaught (in promise): TypeError: Cannot read property 'emit' of undefined
TypeError: Cannot read property 'emit' of undefined
    at new HomeComponent (http://localhost:4200/main.bundle.js:853:25)
    at new Wrapper_HomeComponent (/AppModule/HomeComponent/wrapper.ngfactory.js:7:18)
    at CompiledTemplate.proxyViewClass.View_HomeComponent_Host0.createInternal (/AppModule/HomeComponent/host.ngfactory.js:15:29)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:96164:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:96620:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:47296:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:67593:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:78259:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:27437:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:27404:26)
    at http://localhost:4200/vendor.bundle.js:27340:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:27340:29)
    at ActivateRoutes.activate (http://localhost:4200/vendor.bundle.js:27314:14)
    at http://localhost:4200/vendor.bundle.js:26882:22
    at resolvePromise (http://localhost:4200/vendor.bundle.js:135342:31) [angular]
    at resolvePromise (http://localhost:4200/vendor.bundle.js:135327:17) [angular]
    at http://localhost:4200/vendor.bundle.js:135376:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:34097:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:135130:40) [angular]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:135007:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:135274:35) [<root>]
ErrorHandler.handleError @ error_handler.js:56
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:246
Zone.runGuarded @ zone.js:129
_loop_1 @ zone.js:429
drainMicroTaskQueue @ zone.js:438
Promise.resolve (async)
scheduleQueueDrain @ zone.js:391
scheduleMicroTask @ zone.js:399
ZoneDelegate.scheduleTask @ zone.js:258
Zone.scheduleMicroTask @ zone.js:165
scheduleResolveOrReject @ zone.js:518
ZoneAwarePromise.then @ zone.js:604
ZoneAwarePromise.all @ zone.js:584
JitCompiler._loadModules @ compiler.js:172
JitCompiler._compileModuleAndComponents @ compiler.js:124
JitCompiler.compileModuleAsync @ compiler.js:90
PlatformRef_._bootstrapModuleWithZone @ application_ref.js:388
PlatformRef_.bootstrapModule @ application_ref.js:363
596 @ main.ts:12
__webpack_require__ @ bootstrap b2b7e48…:52
1262 @ main.bundle.js:14
__webpack_require__ @ bootstrap b2b7e48…:52
webpackJsonpCallback @ bootstrap b2b7e48…:23
(anonymous) @ main.bundle.js:1
zone.js:405Unhandled Promise rejection: Cannot read property 'emit' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'emit' of undefined
    at new HomeComponent (http://localhost:4200/main.bundle.js:853:25)
    at new Wrapper_HomeComponent (/AppModule/HomeComponent/wrapper.ngfactory.js:7:18)
    at CompiledTemplate.proxyViewClass.View_HomeComponent_Host0.createInternal (/AppModule/HomeComponent/host.ngfactory.js:15:29)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:96164:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:96620:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:47296:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:67593:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:78259:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:27437:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:27404:26)
    at http://localhost:4200/vendor.bundle.js:27340:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:27340:29)
    at ActivateRoutes.activate (http://localhost:4200/vendor.bundle.js:27314:14)
    at http://localhost:4200/vendor.bundle.js:26882:22 TypeError: Cannot read property 'emit' of undefined
    at new HomeComponent (http://localhost:4200/main.bundle.js:853:25)
    at new Wrapper_HomeComponent (/AppModule/HomeComponent/wrapper.ngfactory.js:7:18)
    at CompiledTemplate.proxyViewClass.View_HomeComponent_Host0.createInternal (/AppModule/HomeComponent/host.ngfactory.js:15:29)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:96164:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:96620:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:47296:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:67593:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:78259:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:27437:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:27404:26)
    at http://localhost:4200/vendor.bundle.js:27340:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:27340:29)
    at ActivateRoutes.activate (http://localhost:4200/vendor.bundle.js:27314:14)
    at http://localhost:4200/vendor.bundle.js:26882:22
consoleError @ zone.js:405
_loop_1 @ zone.js:434
drainMicroTaskQueue @ zone.js:438
Promise.resolve (async)
scheduleQueueDrain @ zone.js:391
scheduleMicroTask @ zone.js:399
ZoneDelegate.scheduleTask @ zone.js:258
Zone.scheduleMicroTask @ zone.js:165
scheduleResolveOrReject @ zone.js:518
ZoneAwarePromise.then @ zone.js:604
ZoneAwarePromise.all @ zone.js:584
JitCompiler._loadModules @ compiler.js:172
JitCompiler._compileModuleAndComponents @ compiler.js:124
JitCompiler.compileModuleAsync @ compiler.js:90
PlatformRef_._bootstrapModuleWithZone @ application_ref.js:388
PlatformRef_.bootstrapModule @ application_ref.js:363
596 @ main.ts:12
__webpack_require__ @ bootstrap b2b7e48…:52
1262 @ main.bundle.js:14
__webpack_require__ @ bootstrap b2b7e48…:52
webpackJsonpCallback @ bootstrap b2b7e48…:23
(anonymous) @ main.bundle.js:1
zone.js:407Error: Uncaught (in promise): TypeError: Cannot read property 'emit' of undefined
TypeError: Cannot read property 'emit' of undefined
    at new HomeComponent (http://localhost:4200/main.bundle.js:853:25)
    at new Wrapper_HomeComponent (/AppModule/HomeComponent/wrapper.ngfactory.js:7:18)
    at CompiledTemplate.proxyViewClass.View_HomeComponent_Host0.createInternal (/AppModule/HomeComponent/host.ngfactory.js:15:29)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:96164:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:96620:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:47296:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:67593:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:78259:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:27437:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:27404:26)
    at http://localhost:4200/vendor.bundle.js:27340:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:27340:29)
    at ActivateRoutes.activate (http://localhost:4200/vendor.bundle.js:27314:14)
    at http://localhost:4200/vendor.bundle.js:26882:22
    at new HomeComponent (http://localhost:4200/main.bundle.js:853:25)
    at new Wrapper_HomeComponent (/AppModule/HomeComponent/wrapper.ngfactory.js:7:18)
    at CompiledTemplate.proxyViewClass.View_HomeComponent_Host0.createInternal (/AppModule/HomeComponent/host.ngfactory.js:15:29)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:96164:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:96620:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:47296:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:67593:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:78259:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:27437:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:27404:26)
    at http://localhost:4200/vendor.bundle.js:27340:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:27340:29)
    at ActivateRoutes.activate (http://localhost:4200/vendor.bundle.js:27314:14)
    at http://localhost:4200/vendor.bundle.js:26882:22
    at resolvePromise (http://localhost:4200/vendor.bundle.js:135342:31) [angular]
    at resolvePromise (http://localhost:4200/vendor.bundle.js:135327:17) [angular]
    at http://localhost:4200/vendor.bundle.js:135376:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:34097:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:135130:40) [angular]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:135007:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:135274:35) [<root>]
consoleError @ zone.js:407
_loop_1 @ zone.js:434
drainMicroTaskQueue @ zone.js:438
Promise.resolve (async)
scheduleQueueDrain @ zone.js:391
scheduleMicroTask @ zone.js:399
ZoneDelegate.scheduleTask @ zone.js:258
Zone.scheduleMicroTask @ zone.js:165
scheduleResolveOrReject @ zone.js:518
ZoneAwarePromise.then @ zone.js:604
ZoneAwarePromise.all @ zone.js:584
JitCompiler._loadModules @ compiler.js:172
JitCompiler._compileModuleAndComponents @ compiler.js:124
JitCompiler.compileModuleAsync @ compiler.js:90
PlatformRef_._bootstrapModuleWithZone @ application_ref.js:388
PlatformRef_.bootstrapModule @ application_ref.js:363
596 @ main.ts:12
__webpack_require__ @ bootstrap b2b7e48…:52
1262 @ main.bundle.js:14
__webpack_require__ @ bootstrap b2b7e48…:52
webpackJsonpCallback @ bootstrap b2b7e48…:23
(anonymous) @ main.bundle.js:1
```

**Comment by jonathan-casarrubias** [comment]
Hi @rajweb thanks for reaching us out.

the emit seems to be undefined because in the latest versions you need to wait until the 'onReady' method is fired.

````js
  constructor(private realTime: RealTime) {  this.realTime.IO.emit('test', 'hello publish it');
        this.realTime.onReady().subscribe(() => {
  	     this.realTime.IO.emit('test', 'raj angular');
             this.realTime.IO.on('test').subscribe((msg: any) => console.log('Realtime Cli Msg ='+ msg));
        });
  }
````

Also I see you are sending a message Client <-> Client and that is not the way Socket IO works, the IO methods you receive within the realtime module are facades of a socket io client.

So the first emit is actually sending a test event to the server, but then the server should distribute to others the message, please see socket.io documention for more info about it.

**Comment by rajweb** [comment]
thanxs jonathan...solutions works
