### ISSUE TITLE
Cannot build sdk on 13.1

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/loopback-sdk-builder#460]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.13.1 (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

If using the latest 13.1, then I cannot build and get the following

```
D:\GM Work Box\dataon\Flutter Asia\flutterasia-server>npm run build:sdk

> pmjakarta-server@1.0.0 build:sdk D:\GM Work Box\dataon\Flutter Asia\flutterasia-server
> lb-sdk server/server.js ./client/sdk -l angular2 -d ng2web --io enabled

D:\GM Work Box\dataon\Flutter Asia\flutterasia-server\node_modules\@mean-expert\loopback-sdk-builder\lib\angular2\index.js:20
ejs.filters.q = (obj) => JSON.stringify(obj, null, 2);
              ^

TypeError: Cannot set property 'q' of undefined
    at Object.<anonymous> (D:\GM Work Box\dataon\Flutter Asia\flutterasia-server\node_modules\@mean-expert\loopback-sdk-builder\lib\angular2\index.js:20:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\GM Work Box\dataon\Flutter Asia\flutterasia-server\node_modules\@mean-expert\loopback-sdk-builder\index.js:1:82)
    at Module._compile (module.js:569:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pmjakarta-server@1.0.0 build:sdk: `lb-sdk server/server.js ./client/sdk -l angular2 -d ng2web --io enabled`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pmjakarta-server@1.0.0 build:sdk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\julia\AppData\Roaming\npm-cache\_logs\2017-07-20T10_42_01_161Z-debug.log
```

Its working again if I revert to 13

**Comment by jonathan-casarrubias** [comment]
@dmastag well that is really strange, since the only difference between 13 and 13.1 is a return type in here

https://github.com/mean-expert-official/loopback-sdk-builder/blob/development/lib/angular2/shared/config.ejs#L82

which modifies from

````js
  public static isSecureWebSocketsSet(): void {
    return LoopBackConfig.secure;
  }
````

to

````js
  public static isSecureWebSocketsSet(): boolean {
    return LoopBackConfig.secure;
  }
````

there are no other changes, the one you are getting is because a missing filter in the ejs library... Maybe it was not correctly installed while updating the version... But I can not see a way the hot fix could make a difference in this issue between 13 and 13.1

**Comment by dmastag** [comment]
After reinstalling its working. Not sure what the problem was
Thanks anyway!
