### ISSUE TITLE
ReferenceError: Params is not defined in Customer Model Base on User.

### ISSUE THREAD

**Issue by gvsdan** [mean-expert-official/loopback-sdk-builder#97]
I just update the sdk builder and try it to generate de sdk in my app but i got this error.

```
throw err;
  ^

ReferenceError: ejs:129
    127|     return result.map((result: <%- modelName %> | Array<<%- modelName %>>) => Array.isArray(result)
    128|                              ? result.map((instance: <%- modelName %>)=> new <%-: modelName %>(instance))
 >> 129|                              : new <%-: modelName %>(result));<%
    130| } else { %>;
    131|     return result;<%
    132| } %>

params is not defined
    at eval (eval at <anonymous> (/Users/Dan/development/fatloc-api/node_modules/loopback-sdk-builder/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:91:5)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/Users/Dan/development/fatloc-api/node_modules/loopback-sdk-builder/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1343)
    at eval (eval at <anonymous> (/Users/Dan/development/fatloc-api/node_modules/loopback-sdk-builder/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:157:19)
    at /Users/Dan/development/fatloc-api/node_modules/loopback-sdk-builder/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/Dan/development/fatloc-api/node_modules/loopback-sdk-builder/node_modules/ejs/lib/ejs.js:293:13)
    at /Users/Dan/development/fatloc-api/node_modules/loopback-sdk-builder/lib/angular2/index.js:199:13
    at Array.forEach (native)
    at Object.generate (/Users/Dan/development/fatloc-api/node_modules/loopback-sdk-builder/lib/angular2/index.js:194:10)
    at EventEmitter.runGenerator (/Users/Dan/development/fatloc-api/node_modules/loopback-sdk-builder/bin/lb-sdk:67:33)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at /Users/Dan/development/fatloc-api/server/node_modules/loopback-boot/lib/executor.js:61:9
    at /Users/Dan/development/fatloc-api/server/node_modules/async/lib/async.js:251:17
    at /Users/Dan/development/fatloc-api/server/node_modules/async/lib/async.js:154:25
    at /Users/Dan/development/fatloc-api/server/node_modules/async/lib/async.js:248:21
    at /Users/Dan/development/fatloc-api/server/node_modules/async/lib/async.js:612:34
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
    at process.fallback (/Users/Dan/development/fatloc-api/server/node_modules/async-listener/index.js:450:15)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
```

**Comment by jonathan-casarrubias** [comment]
@gvsdan How did you update the builder?

It seems you still have the loopback-sdk-builder installed, that module is deprecated already.

You should uninstall that module and then install @mean-expert/loopback-sdk-builder that will create a @mean-expert folder within node_modules.

Please see the new Wiki docs for guidance.

Cheers!
Jon
